apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  labels:
    app: apigateway
spec:
  replicas: 1 #5
  template:
    metadata:
      name: apigateway
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: carmanagement.azurecr.io/apigateway:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: apigateway

---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  selector:
    app: apigateway
  ports:
    - port: 80
  type: LoadBalancer