apiVersion: apps/v1
kind: Deployment
metadata:
  name: carapi
  labels:
    app: carapi
spec:
  replicas: 1 #5
  template:
    metadata:
      name: carapi
      labels:
        app: carapi
    spec:
      containers:
      - name: carapi
        image: carmanagement.azurecr.io/carapi:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: carapi

---
apiVersion: v1
kind: Service
metadata:
  name: carapi
spec:
  selector:
    app: carapi
  ports:
    - port: 80
  type: LoadBalancer