apiVersion: apps/v1
kind: Deployment
metadata:
  name: spendingsapi
  labels:
    app: spendingsapi
spec:
  replicas: 1 #5
  template:
    metadata:
      name: spendingsapi
      labels:
        app: spendingsapi
    spec:
      containers:
      - name: spendingsapi
        image: carmanagement.azurecr.io/spendingsapi:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: spendingsapi

---
apiVersion: v1
kind: Service
metadata:
  name: spendingsapi
spec:
  selector:
    app: spendingsapi
  ports:
    - port: 80
  type: LoadBalancer