apiVersion: apps/v1
kind: Deployment
metadata:
  name: transactionsapi
  labels:
    app: transactionsapi
spec:
  replicas: 1 #5
  template:
    metadata:
      name: transactionsapi
      labels:
        app: transactionsapi
    spec:
      containers:
      - name: transactionsapi
        image: carmanagement.azurecr.io/transactionsapi:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: transactionsapi

---
apiVersion: v1
kind: Service
metadata:
  name: transactionsapi
spec:
  selector:
    app: transactionsapi
  ports:
    - port: 80
  type: LoadBalancer