apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
  labels:
    app: userapi
spec:
  replicas: 1 #5
  template:
    metadata:
      name: userapi
      labels:
        app: userapi
    spec:
      containers:
      - name: userapi
        image: carmanagement.azurecr.io/userapi:latest
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: userapi

---
apiVersion: v1
kind: Service
metadata:
  name: userapi
spec:
  selector:
    app: userapi
  ports:
    - port: 80
  type: LoadBalancer